//=======================================================
//  This code is generated by Terasic System Builder
//  Updated for IHS Project Mapping - UFPE
//=======================================================

module pcihello(

	//////////// CLOCK //////////
	CLOCK_50, 	// BANK 4
	CLOCK2_50, 	// BANK 7
	CLOCK3_50, 	// BANK 3A

	//////////// LED (High Active) //////////
	LEDG,
	LEDR,

	//////////// KEY (Active Low) //////////
	KEY,

	//////////// SWITCHES //////////
	SW,
	
	//////////// SEG7 (Low Active) //////////
	HEX0,
	HEX1,
	HEX2,
	HEX3,
	HEX4,
	HEX5,
	HEX6,
	HEX7,

	//////////// PCIe //////////
	PCIE_PERST_N,
	PCIE_REFCLK_P,
	PCIE_RX_P,
	PCIE_TX_P,
	PCIE_WAKE_N,

	//////////// Fan Control //////////
	FAN_CTRL 
);

//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;
input 		          		CLOCK2_50;
input 		          		CLOCK3_50;

//////////// LED (High Active) //////////
output		     [8:0]		LEDG;
output		    [17:0]		LEDR;

//////////// KEY (Active Low) //////////
input 		     [3:0]		KEY;
input            [17:0]     SW;

//////////// SEG7 (Low Active) //////////
output		     [6:0]		HEX0;
output		     [6:0]		HEX1;
output		     [6:0]		HEX2;
output		     [6:0]		HEX3;
output		     [6:0]		HEX4;
output		     [6:0]		HEX5;
output		     [6:0]		HEX6;
output		     [6:0]		HEX7;

//////////// PCIe //////////
input 		          		PCIE_PERST_N;
input 		          		PCIE_REFCLK_P;
input 		     [1:0]		PCIE_RX_P;
output		     [1:0]		PCIE_TX_P;
output		          		PCIE_WAKE_N;

//////////// Fan Control //////////
inout 		          		FAN_CTRL;


//=======================================================
//  REG/WIRE declarations (Passo 11)
//=======================================================
// Todos os barramentos novos foram padronizados em 32 bits para 
// facilitar as operações de leitura/escrita do driver PCI no Linux.

wire [31:0] hex_bus;       // Conecta HEX0, HEX1, HEX2, HEX3
wire [31:0] hex_bus2;      // Conecta HEX4, HEX5
wire [31:0] hex_bus3;      // Conecta HEX6, HEX7
wire [31:0] sw_bus;        // Conecta os 18 Slide Switches (Chaves)
wire [31:0] push_bus;      // Conecta os 4 Push-buttons (Botões)
wire [31:0] red_bus;       // Conecta os 18 LEDs Vermelhos
wire [31:0] green_bus;     // Conecta os 9 LEDs Verdes
wire [31:0] fan_bus;       // Conecta o circuito de Fan Control


//=======================================================
//  Structural coding (Passo 12)
//=======================================================

    pcihellocore u0 (
        // Conexões nativas da infraestrutura PCI Express
        .pcie_hard_ip_0_rx_in_rx_datain_0       (PCIE_RX_P[0]),
        .pcie_hard_ip_0_tx_out_tx_dataout_0     (PCIE_TX_P[0]),
        .pcie_hard_ip_0_powerdown_pll_powerdown (PCIE_WAKE_N),
        .pcie_hard_ip_0_powerdown_gxb_powerdown (PCIE_WAKE_N),
        .pcie_hard_ip_0_refclk_export           (PCIE_REFCLK_P),
        .pcie_hard_ip_0_pcie_rstn_export          (PCIE_PERST_N),

        // Seus novos mapeamentos exportados do Platform Designer (QSYS)
        .hex_display_external_connection_export   (hex_bus),
        .hex_display2_external_connection_export  (hex_bus2),
        .hex_display3_external_connection_export  (hex_bus3),
        .switches_external_connection_export      (sw_bus),
        .push_buttons_external_connection_export  (push_bus),
        .red_leds_external_connection_export      (red_bus),
        .green_leds_external_connection_export    (green_bus),
        .fan_control_external_connection_export   (fan_bus)
    );


//=======================================================
//  Atrbuições de Pinos do Hardware (Passo 13)
//=======================================================

// ---------------- SALVAGUARDA DO COOLER (Passo 13.1) ----------------
// IMPORTANTE: Modificado de 1'b0 para 1'bz (alta impedância) ou controlado pelo bus.
// O bit de reset configurado no QSYS deve ser 1 para mantê-lo ligado por segurança.
assign FAN_CTRL = fan_bus[0]; 

// Mapeamento dos blocos de Displays de 7 segmentos (7 bits por display)
assign HEX0 = hex_bus[6:0];
assign HEX1 = hex_bus[14:8];
assign HEX2 = hex_bus[22:16];
assign HEX3 = hex_bus[30:24];

assign HEX4 = hex_bus2[6:0];
assign HEX5 = hex_bus2[14:8];

assign HEX6 = hex_bus3[6:0];
assign HEX7 = hex_bus3[14:8];

// Mapeamento das saídas dos LEDs (Ativos em nível Alto)
assign LEDR = red_bus[17:0];   // 18 LEDs Vermelhos dispostos acima das chaves
assign LEDG = green_bus[8:0];  // 9 LEDs Verdes dispostos acima dos botões

// Mapeamento das entradas físicas (Chaves e Botões) para os registradores
assign sw_bus[17:0]   = SW;    // Leitura completa de todas as 18 chaves deslizantes
assign push_bus[3:0]  = KEY;   // Leitura completa dos 4 botões de pressão (Ativos em Baixo)

endmodule