//=======================================================
// This code is generated by Terasic System Builder
// Updated for IHS Project Mapping - UFPE
//=======================================================

module pcihello(

    //////////// CLOCK //////////
    CLOCK_50,
    CLOCK2_50,
    CLOCK3_50,

    //////////// LED (High Active) //////////
    LEDG,
    LEDR,

    //////////// KEY (Active Low) //////////
    KEY,

    //////////// SWITCHES //////////
    SW,

    //////////// SEG7 (Low Active) //////////
    HEX0,
    HEX1,
    HEX2,
    HEX3,
    HEX4,
    HEX5,
    HEX6,
    HEX7,

    //////////// PCIe //////////
    PCIE_PERST_N,
    PCIE_REFCLK_P,
    PCIE_RX_P,
    PCIE_TX_P,
    PCIE_WAKE_N,

    //////////// Fan Control //////////
    FAN_CTRL
);

//=======================================================
// PORT declarations
//=======================================================

//////////// CLOCK //////////
input CLOCK_50;
input CLOCK2_50;
input CLOCK3_50;

//////////// LED (High Active) //////////
output [8:0]  LEDG;
output [17:0] LEDR;

//////////// KEY (Active Low) //////////
input [3:0] KEY;

//////////// SWITCHES //////////
input [17:0] SW;

//////////// SEG7 (Low Active) //////////
output [6:0] HEX0;
output [6:0] HEX1;
output [6:0] HEX2;
output [6:0] HEX3;
output [6:0] HEX4;
output [6:0] HEX5;
output [6:0] HEX6;
output [6:0] HEX7;

//////////// PCIe //////////
input        PCIE_PERST_N;
input        PCIE_REFCLK_P;
input  [1:0] PCIE_RX_P;
output [1:0] PCIE_TX_P;
output       PCIE_WAKE_N;

//////////// Fan Control //////////
inout FAN_CTRL;


//=======================================================
// REG/WIRE declarations
//=======================================================

wire [31:0] hex_bus;
wire [31:0] hex_bus2;
wire [31:0] hex_bus3;
wire [31:0] sw_bus;
wire [31:0] keys_bus;
wire [31:0] red_bus;
wire [31:0] green_bus;
wire [31:0] fan_bus;


//=======================================================
// Structural coding
//=======================================================

pcihellocore u0 (
    // PCI Express
    .pcie_hard_ip_0_rx_in_rx_datain_0       (PCIE_RX_P[0]),
    .pcie_hard_ip_0_tx_out_tx_dataout_0     (PCIE_TX_P[0]),
    .pcie_hard_ip_0_powerdown_pll_powerdown (PCIE_WAKE_N),
    .pcie_hard_ip_0_powerdown_gxb_powerdown (PCIE_WAKE_N),
    .pcie_hard_ip_0_refclk_export           (PCIE_REFCLK_P),
    .pcie_hard_ip_0_pcie_rstn_export        (PCIE_PERST_N),

    // Displays
    .hex_display_external_connection_export  (hex_bus),
    .hex_display2_external_connection_export (hex_bus2),
    .hex_display3_external_connection_export (hex_bus3),


    .switches_external_connection_export     (sw_bus),
    .push_buttons_external_connection_export (keys_bus),

    // LEDs e Fan vindos do QSYS
    .red_leds_external_connection_export     (red_bus),
    .green_leds_external_connection_export   (green_bus),
    .fan_control_external_connection_export  (fan_bus)
);


//=======================================================
// Atribuições de pinos do hardware
//=======================================================

// Fan control
assign FAN_CTRL = 1'bz;

// Displays de 7 segmentos
assign HEX0 = hex_bus[6:0];
assign HEX1 = hex_bus[14:8];
assign HEX2 = hex_bus[22:16];
assign HEX3 = hex_bus[30:24];

assign HEX4 = hex_bus2[6:0];
assign HEX5 = hex_bus2[14:8];

assign HEX6 = hex_bus3[6:0];
assign HEX7 = hex_bus3[14:8];

//=======================================================
// Periféricos não utilizados pela aplicação
//=======================================================

// Aterra a entrada do Qsys para evitar lixo lógico
assign sw_bus = 18'd0; 
assign keys_bus = 4'd0;

// LEDR[0] testando direto a chave SW[0] para debug físico
assign LEDR[0] = SW[0];

// Desliga o resto dos LEDs
assign LEDR[17:1] = 17'd0;

// LEDG continua vindo do QSYS
// Conecta os 9 primeiros bits do barramento direto nos 9 LEDs verdes
assign LEDG = green_bus[8:0];

// Como só o canal 0 do PCIe está sendo usado, deixa o canal 1 em nível baixo
assign PCIE_TX_P[1] = 1'b0;

endmodule